### ISSUE TITLE
[bindl] Error building vscode-shellcheck on M1: dyld[71190]: missing symbol called

### ISSUE THREAD

**Issue by timonwong** [vscode-shellcheck/vscode-shellcheck#719] opened 2022-08-31 01:57 UTC
It seems bindl dependes on some native library which does not work on darwin arm64.

```
npx bindl
  ⠋ downloading and extracting https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz
  ⠋ downloading and extracting https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.armv6hf.tar.xz
  ⠋ downloading and extracting https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.aarch64.tar.xz
  ⠋ downloading and extracting https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.darwin.x86_64.tar.xz
  ⠋ downloading and extracting https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.zip
dyld[71190]: missing symbol called
zsh: killed     npx bindl
```

**Comment by timonwong** [comment] 2022-08-31 02:04
After commenting out "xz" stuffs in `bindl.config.js`, it works. Seems a problem extracting xz files

**Comment by timonwong** [comment] 2022-08-31 02:05
Maybe related: https://github.com/addaleax/lzma-native/issues/127

**Comment by felipecrs** [comment] 2022-08-31 02:07
Can you check which version of lzma-native is contained in your node_modules?

**Comment by timonwong** [comment] 2022-08-31 02:13
@felipecrs v0.8.6. Maybe wrong version of node? I've have a clean setup which node is v18.8.0

**Comment by felipecrs** [comment] 2022-08-31 02:15
I would recommend you use [Volta](https://volta.sh/) to manage your Node version, as it's what this repository is configured to use in CI too.

With Volta you don't need to do anything, but if you want to ensure the correct version of node, check:

https://github.com/vscode-shellcheck/vscode-shellcheck/blob/c5afa3841c8d18630cba1381e4046e159516eead/package.json#L252-L255

**Comment by felipecrs** [comment] 2022-08-31 02:16
But I think the issue is indeed caused by the linked issue in lzma-native you mentioned, unfortunately.

**Comment by timonwong** [comment] 2022-08-31 02:21
> But I think the issue is indeed caused by the linked issue in lzma-native you mentioned, unfortunately.

Using volta is OK to me now 🎉  . Though I've downgrade node v18 to v14 (homebrewed version), it will still fail with error "missing symbol called".
So maybe there is a problem in homebrew build (node API is not compatible, maybe).

**Comment by felipecrs** [comment] 2022-10-26 17:53
Node is now v16 (it's the one which comes with VSCode 1.66). Maybe we can close this issue?

**Closed** 2022-11-17 04:52 UTC
