### ISSUE TITLE
[Feature Request] Quick fix for "ignore this line"

### ISSUE THREAD

**Issue by lonix1** [vscode-shellcheck/vscode-shellcheck#616] opened 2022-06-07 01:27 UTC
It would be nice to have a quick fix action for "ignore this line", to ignore all errors/warnings for that line.

So after choosing the quick fix, it would prepend that line with
````sh
# shellcheck disable=SC1234,SC5678
````

**Comment by felipecrs** [comment] 2022-06-07 01:41
Duplicate of #116

**Closed** 2022-06-07 01:41 UTC
